### PR TITLE
chore: azule -> pyzule

### PR DESCRIPTION
**Pull request by asdfzxcvbn**
this PR changes the FLEX submodule to my fork (to fix linux compilation) while i wait for [my PR](https://github.com/FLEXTool/FLEX/pull/696) to be merged.

speaking of FLEX.. it was never even being compiled. `SUBMODULES` wasn't being used correctly, so i have no idea how it was working before.

i also removed the Cephei frameworks from the repo, as they'll be injected automatically with pyzule.

### CODE REVIEW

**Comment by SoCuul** [comment]
Would it be possible to stick with the upstream FLEX repo until your PR gets merged? Just trying to stay consistent.

**Comment by asdfzxcvbn** [comment]
> Would it be possible to stick with the upstream FLEX repo until your PR gets merged? Just trying to stay consistent.

i guess so, but then compiling wont work on linux again, so i wont really be able to help as much

**Comment by SoCuul** [comment]
Has this pr fixed the SUBMODULES problem not compiling FLEX?

**Comment by asdfzxcvbn** [comment]
> Has this pr fixed the SUBMODULES problem not compiling FLEX?

yep!

**Comment by SoCuul** [comment]
> > Has this pr fixed the SUBMODULES problem not compiling FLEX?
> 
> yep!

Thank you so much! I'll test this on my machine as soon as possible, then merge it into main.

**Comment by SoCuul** [comment]
Thank you so much for your help with all of this!

**Comment by SoCuul** [comment]
btw @asdfzxcvbn as the author of the project, would it be hard to migrate the pyzule usage to cyan?

**Comment by asdfzxcvbn** [comment]
> btw @asdfzxcvbn as the author of the project, would it be hard to migrate the pyzule usage to cyan?

not at all, i can open a PR later if you'd like. the installation method is much better, too, and basically all flags have remained unchanged in cyan

**Comment by SoCuul** [comment]
> > btw @asdfzxcvbn as the author of the project, would it be hard to migrate the pyzule usage to cyan?
> 
> not at all, i can open a PR later if you'd like. the installation method is much better, too, and basically all flags have remained unchanged in cyan

that'd be great! no rush at all, i'm sure not in any of one haha

**Comment by asdfzxcvbn** [comment]
will work on it now

**Comment by SoCuul** [comment]
by the way do you have any expertise with NSURLRequest? it's behaviour is pretty much the one thing preventing the new downloading code from being properly implemented.

**Comment by asdfzxcvbn** [comment]
> by the way do you have any expertise with NSURLRequest? it's behaviour is pretty much the one thing preventing the new downloading code from being properly implemented.

just NSURLRequest? not even the actual networking part, NSURLSession? what's the issue?

**Comment by SoCuul** [comment]
> > by the way do you have any expertise with NSURLRequest? it's behaviour is pretty much the one thing preventing the new downloading code from being properly implemented.
> 
> just NSURLRequest? not even the actual networking part, NSURLSession? what's the issue?

https://github.com/SoCuul/SCInsta/discussions/132

**Comment by SoCuul** [comment]
dont mind me, just accidentally fucked up the entire branch while trying to merge it 😭 git will be the end of me

**Pull request merged**
