### PR TITLE
feat: add focus mode

### PR DESCRIPTION
**Pull request by vlourme**
Resynchronized from https://github.com/SoCuul/BHInsta/pull/8

### CODE REVIEW

**Comment by SoCuul** [comment]
Hey, I'm just getting around to this now.

I'm not completely sure what the point of "hide feed posts" is.
Isn't that pretty much the core function of Instagram, at the most basic level?

**Comment by asdfzxcvbn** [comment]
maybe some people only use instagram for DMs or something similar. it could be useful for some people

**Comment by SoCuul** [comment]
> maybe some people only use instagram for DMs or something similar. it could be useful for some people

In that case it could be useful to just hide the feed page altogether.

**Comment by vlourme** [comment]
My ultimate goal (that I might try on my fork) is to revive "Threads From Instagram", a deleted from App Store, simplified instagram application with only messages, stories and camera (see here: https://youtu.be/ce_jBjGZmBk). If it doesn't fit this fork, I can understand. Up to you

**Comment by SoCuul** [comment]
Unfortunately I don't think this will really fit the general-purpose direction of this fork, but I'm interested to see what you can do with your fork!

On another note, I can't believe they made an app called threads, killed it off, and made another app called threads for a completely different purpose.

**Comment by vlourme** [comment]
I think we should close this PR then. Also, unrelated, but are you able to run tweaked IG on iOS simulator? I lose a lot of time sideloading on my phone every time.

**Comment by SoCuul** [comment]
I've never tried personally, I always sideload to my actual device. Usually on a wired connection, it only takes about 15-20 seconds.

**Comment by SoCuul** [comment]
Also @vlourme, the deploy script I have in `build-dev.sh` is essentially just this. My workflow allows me to run the one shell script and it automatically builds, signs and sideloads the app onto my device in about a minute.

```sh
#!/usr/bin/env bash
if [ "$#" -lt 1 ]
then
    echo
    echo "Usage: ./deploy.sh <appname> [nowifi-boolean]"
    echo
    exit 1
fi

[[ -n "$2" ]] && args="--no-wifi" || args=""

ios-deploy --bundle "$1/ipas/signed.ipa" $args
```

**Comment by vlourme** [comment]
Good to know, I use Sideloadly each time. I will try this way. Thank you

**Pull request closed without merging**
